project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.contrib.sitemaps.views import sitemap


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search.urls')),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('sitemap.xml', sitemap),
    path('', include(wagtail_urls)),

]

if settings.ENV != "PROD":
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/search/urls.py
from django.urls import path
from .views import search_view


app_name = "search"
urlpatterns = [
    path('search/', search_view, name="search"),
    ]

project/templates/base.html
{% load static wagtailcore_tags wagtailuserbar %}
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
        {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}
        {% endblock %}
        {% block title_suffix %}
        {% wagtail_site as current_site %}
        {% if current_site and current_site.site_name %}- {{ current_site.site_name }}{% endif %}
        {% endblock %}
    </title>
    {% if page.search_description %}
    <meta name="description" content="{{ page.search_description }}"/>
    {% endif %}
    <link rel="icon" href="{% static 'logos/favicon.ico' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex flex-column min-vh-100">
<!-- https://www.happyhues.co/palettes/8 -->

<nav class="navbar navbar-expand-lg shadow" style="background-color: white;">
    <div class="container-fluid" style="background-color: white;">
        <a class="navbar-brand" href="{% slugurl 'index' %}">PyGabDev</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% slugurl 'projets' %}">Projets</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% slugurl 'blog' %}">Blog</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-disabled="true" href="{% slugurl 'contact' %}">Contact</a>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'search:search' %}">
                <input class="form-control me-2" type="text" name="query" value="{{ search_query }}">
                <input class="btn custom-btn" type="submit" value="Rechercher">
            </form>
        </div>
    </div>
</nav>

{% wagtailuserbar %}
{% block body %}{% endblock %}

<div class="container-fluid text-center mt-auto p-5 rounded" style="background-color: white;">

    <hr>

    <footer><p>© 2024 PyGabDev - Tous droits réservés
        {% if request.user.is_superuser %}
        -
        <a href="{% url 'admin:index' %}">Administration avancée</a>
        {% endif %}</p>
        <div class="d-flex align-items-center justify-content-center">
            <a aria-label="Réseau X de Gabriel Trouvé" href="https://twitter.com/GabrielTrouve" target="_blank"><img
                    src="{% static 'logos/x.png' %}" width="40"
                    height="auto"></a> <a aria-label="Réseau Linkedin de Gabriel Trouvé"
                                          href="https://www.linkedin.com/in/gabriel-trouv%C3%A9-b6a2bb159/"
                                          target="_blank"><img
                src="{% static 'logos/l.png' %}" width="40" height="auto"></a> <a aria-label="GitHub de Gabriel Trouvé"
                                                                                  href="https://github.com/gabigab117"
                                                                                  target="_blank"><img
                src="{% static 'logos/g.png' %}" width="40" height="auto"></a></div>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>